import "@/styles/globals.css";

import { BIABAnalytics } from "@biab-dev/sdk/react-analytics";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

const BIAB_SITE_ID = process.env.BIAB_SITE_ID;
const BIAB_BASE_URL =
  process.env.NEXT_PUBLIC_BIAB_PACKAGE_API_BASE_URL ??
  process.env.BIAB_PACKAGE_API_BASE_URL;
const BIAB_PUBLIC_KEY = process.env.NEXT_PUBLIC_BIAB_PUBLIC_KEY;

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        {BIAB_SITE_ID && BIAB_BASE_URL && BIAB_PUBLIC_KEY ? (
          <BIABAnalytics
            siteId={BIAB_SITE_ID}
            baseUrl={BIAB_BASE_URL}
            apiKey={BIAB_PUBLIC_KEY}
          />
        ) : null}
      </body>
    </html>
  );
}
